[2025-02-18 15:35:29,793][flwr][WARNING] - 
Setting `min_available_clients` lower than `min_fit_clients` or
`min_evaluate_clients` can cause the server to fail when there are too few clients
connected to the server. `min_available_clients` must be set to a value larger
than or equal to the values of `min_fit_clients` and `min_evaluate_clients`.

[2025-02-18 15:35:29,794][flwr][INFO] - Starting Flower simulation, config: num_rounds=5, no round_timeout
[2025-02-18 15:35:33,977][flwr][INFO] - Flower VCE: Ray initialized with resources: {'CPU': 16.0, 'node:__internal_head__': 1.0, 'memory': 17803638375.0, 'object_store_memory': 8901819187.0, 'accelerator_type:M4000': 1.0, 'node:10.40.177.142': 1.0, 'GPU': 1.0}
[2025-02-18 15:35:33,977][flwr][INFO] - Optimize your simulation with Flower VCE: https://flower.ai/docs/framework/how-to-run-simulations.html
[2025-02-18 15:35:33,977][flwr][INFO] - Flower VCE: Resources for each Virtual Client: {'num_cpus': 2, 'num_gpus': 0.5}
[2025-02-18 15:35:33,993][flwr][INFO] - Flower VCE: Creating VirtualClientEngineActorPool with 2 actors
[2025-02-18 15:35:33,993][flwr][INFO] - [INIT]
[2025-02-18 15:35:33,993][flwr][INFO] - Requesting initial parameters from one random client
[2025-02-18 15:35:39,695][flwr][ERROR] - Traceback (most recent call last):
  File "/home/tt603/Desktop/federated_learning/Federated-Framework/.venv/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/tt603/Desktop/federated_learning/Federated-Framework/.venv/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/tt603/Desktop/federated_learning/Federated-Framework/.venv/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/tt603/Desktop/federated_learning/Federated-Framework/.venv/lib/python3.8/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/tt603/Desktop/federated_learning/Federated-Framework/.venv/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/tt603/Desktop/federated_learning/Federated-Framework/.venv/lib/python3.8/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/tt603/Desktop/federated_learning/Federated-Framework/.venv/lib/python3.8/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=8780, ip=10.40.177.142, actor_id=9282c076f7f2006e93517a7701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f2a5a2c0460>)
  File "/home/tt603/Desktop/federated_learning/Federated-Framework/.venv/lib/python3.8/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/tt603/Desktop/federated_learning/Federated-Framework/.venv/lib/python3.8/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/tt603/Desktop/federated_learning/Federated-Framework/.venv/lib/python3.8/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/tt603/Desktop/federated_learning/Federated-Framework/.venv/lib/python3.8/site-packages/flwr/client/client_app.py", line 67, in adaptor_fn
    return client_fn(str(cid))  # type: ignore
  File "/home/tt603/Desktop/federated_learning/Federated-Framework/client.py", line 72, in client_fn
    return FlowerClient(trainloader=trainloader, valloader=valloader, input_dim=input_dim)
TypeError: FlowerClient() takes no arguments

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=8780, ip=10.40.177.142, actor_id=9282c076f7f2006e93517a7701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f2a5a2c0460>)
  File "/home/tt603/Desktop/federated_learning/Federated-Framework/.venv/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: FlowerClient() takes no arguments

[2025-02-18 15:35:39,696][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=8780, ip=10.40.177.142, actor_id=9282c076f7f2006e93517a7701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f2a5a2c0460>)
  File "/home/tt603/Desktop/federated_learning/Federated-Framework/.venv/lib/python3.8/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/tt603/Desktop/federated_learning/Federated-Framework/.venv/lib/python3.8/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/tt603/Desktop/federated_learning/Federated-Framework/.venv/lib/python3.8/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/tt603/Desktop/federated_learning/Federated-Framework/.venv/lib/python3.8/site-packages/flwr/client/client_app.py", line 67, in adaptor_fn
    return client_fn(str(cid))  # type: ignore
  File "/home/tt603/Desktop/federated_learning/Federated-Framework/client.py", line 72, in client_fn
    return FlowerClient(trainloader=trainloader, valloader=valloader, input_dim=input_dim)
TypeError: FlowerClient() takes no arguments

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=8780, ip=10.40.177.142, actor_id=9282c076f7f2006e93517a7701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f2a5a2c0460>)
  File "/home/tt603/Desktop/federated_learning/Federated-Framework/.venv/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: FlowerClient() takes no arguments
[2025-02-18 15:35:39,696][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=8780, ip=10.40.177.142, actor_id=9282c076f7f2006e93517a7701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f2a5a2c0460>)
  File "/home/tt603/Desktop/federated_learning/Federated-Framework/.venv/lib/python3.8/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/tt603/Desktop/federated_learning/Federated-Framework/.venv/lib/python3.8/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/tt603/Desktop/federated_learning/Federated-Framework/.venv/lib/python3.8/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/tt603/Desktop/federated_learning/Federated-Framework/.venv/lib/python3.8/site-packages/flwr/client/client_app.py", line 67, in adaptor_fn
    return client_fn(str(cid))  # type: ignore
  File "/home/tt603/Desktop/federated_learning/Federated-Framework/client.py", line 72, in client_fn
    return FlowerClient(trainloader=trainloader, valloader=valloader, input_dim=input_dim)
TypeError: FlowerClient() takes no arguments

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=8780, ip=10.40.177.142, actor_id=9282c076f7f2006e93517a7701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f2a5a2c0460>)
  File "/home/tt603/Desktop/federated_learning/Federated-Framework/.venv/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: FlowerClient() takes no arguments
[2025-02-18 15:35:39,697][flwr][ERROR] - Traceback (most recent call last):
  File "/home/tt603/Desktop/federated_learning/Federated-Framework/.venv/lib/python3.8/site-packages/flwr/simulation/app.py", line 339, in start_simulation
    hist = run_fl(
  File "/home/tt603/Desktop/federated_learning/Federated-Framework/.venv/lib/python3.8/site-packages/flwr/server/server.py", line 492, in run_fl
    hist, elapsed_time = server.fit(
  File "/home/tt603/Desktop/federated_learning/Federated-Framework/.venv/lib/python3.8/site-packages/flwr/server/server.py", line 93, in fit
    self.parameters = self._get_initial_parameters(server_round=0, timeout=timeout)
  File "/home/tt603/Desktop/federated_learning/Federated-Framework/.venv/lib/python3.8/site-packages/flwr/server/server.py", line 284, in _get_initial_parameters
    get_parameters_res = random_client.get_parameters(
  File "/home/tt603/Desktop/federated_learning/Federated-Framework/.venv/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in get_parameters
    message_out = self._submit_job(message, timeout)
  File "/home/tt603/Desktop/federated_learning/Federated-Framework/.venv/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 108, in _submit_job
    raise ex
  File "/home/tt603/Desktop/federated_learning/Federated-Framework/.venv/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/tt603/Desktop/federated_learning/Federated-Framework/.venv/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/tt603/Desktop/federated_learning/Federated-Framework/.venv/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/tt603/Desktop/federated_learning/Federated-Framework/.venv/lib/python3.8/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/tt603/Desktop/federated_learning/Federated-Framework/.venv/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/tt603/Desktop/federated_learning/Federated-Framework/.venv/lib/python3.8/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/tt603/Desktop/federated_learning/Federated-Framework/.venv/lib/python3.8/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=8780, ip=10.40.177.142, actor_id=9282c076f7f2006e93517a7701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f2a5a2c0460>)
  File "/home/tt603/Desktop/federated_learning/Federated-Framework/.venv/lib/python3.8/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/tt603/Desktop/federated_learning/Federated-Framework/.venv/lib/python3.8/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/tt603/Desktop/federated_learning/Federated-Framework/.venv/lib/python3.8/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/tt603/Desktop/federated_learning/Federated-Framework/.venv/lib/python3.8/site-packages/flwr/client/client_app.py", line 67, in adaptor_fn
    return client_fn(str(cid))  # type: ignore
  File "/home/tt603/Desktop/federated_learning/Federated-Framework/client.py", line 72, in client_fn
    return FlowerClient(trainloader=trainloader, valloader=valloader, input_dim=input_dim)
TypeError: FlowerClient() takes no arguments

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=8780, ip=10.40.177.142, actor_id=9282c076f7f2006e93517a7701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f2a5a2c0460>)
  File "/home/tt603/Desktop/federated_learning/Federated-Framework/.venv/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: FlowerClient() takes no arguments

[2025-02-18 15:35:39,697][flwr][ERROR] - Your simulation crashed :(. This could be because of several reasons. The most common are: 
	 > Sometimes, issues in the simulation code itself can cause crashes. It's always a good idea to double-check your code for any potential bugs or inconsistencies that might be contributing to the problem. For example: 
		 - You might be using a class attribute in your clients that hasn't been defined.
		 - There could be an incorrect method call to a 3rd party library (e.g., PyTorch).
		 - The return types of methods in your clients/strategies might be incorrect.
	 > Your system couldn't fit a single VirtualClient: try lowering `client_resources`.
	 > All the actors in your pool crashed. This could be because: 
		 - You clients hit an out-of-memory (OOM) error and actors couldn't recover from it. Try launching your simulation with more generous `client_resources` setting (i.e. it seems {'num_cpus': 2, 'num_gpus': 0.5} is not enough for your run). Use fewer concurrent actors. 
		 - You were running a multi-node simulation and all worker nodes disconnected. The head node might still be alive but cannot accommodate any actor with resources: {'num_cpus': 2, 'num_gpus': 0.5}.
Take a look at the Flower simulation examples for guidance <https://flower.ai/docs/framework/how-to-run-simulations.html>.
